export const styles = {
    page: {
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: '#0f0f13',
      fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
      position: 'relative',
      overflow: 'hidden',
    },
    blob1: {
      position: 'absolute',
      width: '500px',
      height: '500px',
      borderRadius: '50%',
      background: 'radial-gradient(circle, rgba(232,121,56,0.15) 0%, transparent 70%)',
      top: '-100px',
      right: '-100px',
      pointerEvents: 'none',
    },
    blob2: {
      position: 'absolute',
      width: '400px',
      height: '400px',
      borderRadius: '50%',
      background: 'radial-gradient(circle, rgba(232,121,56,0.08) 0%, transparent 70%)',
      bottom: '-80px',
      left: '-80px',
      pointerEvents: 'none',
    },
    card: {
      background: '#1a1a22',
      border: '1px solid rgba(255,255,255,0.07)',
      borderRadius: '20px',
      padding: '44px 40px',
      width: '100%',
      maxWidth: '420px',
      boxShadow: '0 24px 80px rgba(0,0,0,0.5)',
      position: 'relative',
      zIndex: 1,
    },
    header: {
      textAlign: 'center',
      marginBottom: '32px',
    },
    iconWrap: {
      width: '56px',
      height: '56px',
      borderRadius: '16px',
      background: 'linear-gradient(135deg, #e87938, #c45e1a)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      margin: '0 auto 16px',
      boxShadow: '0 8px 24px rgba(232,121,56,0.35)',
    },
    title: {
      color: '#fff',
      fontSize: '22px',
      fontWeight: '700',
      margin: '0 0 6px',
      letterSpacing: '-0.3px',
    },
    subtitle: {
      color: '#6b6b80',
      fontSize: '14px',
      margin: 0,
    },
    errorBox: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      background: 'rgba(239,68,68,0.1)',
      border: '1px solid rgba(239,68,68,0.25)',
      color: '#f87171',
      borderRadius: '10px',
      padding: '12px 14px',
      fontSize: '13.5px',
      marginBottom: '20px',
    },
    form: {
      display: 'flex',
      flexDirection: 'column',
      gap: '20px',
    },
    field: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
    },
    label: {
      color: '#a0a0b0',
      fontSize: '13px',
      fontWeight: '500',
    },
    inputWrap: {
      position: 'relative',
      display: 'flex',
      alignItems: 'center',
    },
    inputIcon: {
      position: 'absolute',
      left: '14px',
      color: '#4a4a5a',
      pointerEvents: 'none',
    },
    input: {
      width: '100%',
      background: '#111118',
      border: '1px solid rgba(255,255,255,0.08)',
      borderRadius: '10px',
      padding: '12px 14px 12px 44px',
      color: '#fff',
      fontSize: '14px',
      outline: 'none',
      boxSizing: 'border-box',
    },
    eyeBtn: {
      position: 'absolute',
      right: '12px',
      background: 'none',
      border: 'none',
      color: '#4a4a5a',
      cursor: 'pointer',
      padding: '4px',
      display: 'flex',
      alignItems: 'center',
    },
    btn: {
      width: '100%',
      padding: '13px',
      background: 'linear-gradient(135deg, #e87938, #c45e1a)',
      color: '#fff',
      border: 'none',
      borderRadius: '10px',
      fontSize: '15px',
      fontWeight: '600',
      marginTop: '4px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: '0 4px 20px rgba(232,121,56,0.3)',
      cursor: 'pointer',
    },
    spinner: {
      width: '18px',
      height: '18px',
      border: '2px solid rgba(255,255,255,0.3)',
      borderTop: '2px solid #fff',
      borderRadius: '50%',
      animation: 'spin 0.7s linear infinite',
      display: 'inline-block',
    },
  }