/**
 * Run once from your project root:
 *   node convertFont.js
 *
 * Reads amiri.ttf (same folder) and writes src/utils/amiriFont.js
 * with the font embedded as a base64 string.
 */

const fs = require('fs')
const path = require('path')

const ttfPath = path.join(__dirname, 'amiri.ttf')
const outPath = path.join(__dirname, 'src', 'utils', 'amiriFont.js')

if (!fs.existsSync(ttfPath)) {
  console.error('ERROR: amiri.ttf not found. Download it first:\n')
  console.error('  iwr "https://fonts.gstatic.com/s/amiri/v27/J7aRnpd8CGxBHqUpvrIw74NL.ttf" -OutFile "amiri.ttf"\n')
  process.exit(1)
}

const b64 = fs.readFileSync(ttfPath).toString('base64')

fs.writeFileSync(
  outPath,
  `// Auto-generated by convertFont.js — do not edit manually\n` +
  `// Amiri Regular font embedded as base64 (no runtime fetch needed)\n` +
  `const AMIRI_B64 = "${b64}";\n` +
  `export default AMIRI_B64;\n`
)

const kb = Math.round(fs.statSync(outPath).size / 1024)
console.log(`✅  Written: ${outPath}  (${kb} KB)`)